In [6]:
import numpy as np


In [3]:
number_row=2
number_col=3


arrays5= 5* np.ones((number_row, number_col))
arrays5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [7]:
start=10
end=25
step=3
evenly_step=np.arange(start,end,step)

evenly_step

array([10, 13, 16, 19, 22])

In [8]:
identity=np.eye(2)

identity

array([[1., 0.],
       [0., 1.]])

In [10]:
random01=np.random.random((2,3))

random01

array([[0.67086954, 0.67395886, 0.87142254],
       [0.05057194, 0.25504758, 0.87740561]])

In [14]:
randRange=np.random.randint(0,10,(2,3))
randRange

array([[3, 0, 7],
       [2, 6, 9]])

In [17]:
a=np.array([[2,3,5], [2,3,6]])

a





array([[2, 3, 5],
       [2, 3, 6]])

In [19]:
a.dtype

a.shape

(2, 3)

In [22]:
arr = [0,2,4,5,3,7,8,9,5,1]

for i in range (len(arr)):
    if arr[i]%2== 1:
        arr[i]= -arr[i]


oddnumbers= [x for x in arr if x %2==1]

print(oddnumbers)

[-5, -3, -7, -9, -5, -1]


In [14]:
a = np.array([[1 ,2 , 5] , [7,1,3]])
b = np.array([[4,7,8],     [1,5,7]])
c= np.array([[1,2,3],      [8,9,10]])
# stacking arrays together horizontal(column) or vertical(rows) 
abc=np.hstack([a,b,c])
print(abc)

cab=np.vstack([a,b,c])


[[ 1  2  5  4  7  8  1  2  3]
 [ 7  1  3  1  5  7  8  9 10]]


In [13]:
#concat when you put 1 then axis=1 that will use columns , 0 default use vertical 

ab= np.concatenate((a,b) , axis=1)
print(ab)

[[1 2 5 4 7 8]
 [7 1 3 1 5 7]]


In [ ]:
# .npy numpy binary file use to save only sinlge numpy array 
# .npz numpy compressed archive use to save numpy array inside single file 

In [24]:
add1=a+b

add1

array([[ 5,  9, 13],
       [ 8,  6, 10]])

In [5]:
#dot product

b1 = np.array([[4,6] , [2,3] , [2,3]])

dotp= a.dot(b1)

dotp

NameError: name 'np' is not defined

In [28]:
d = np.array([0,0])
e= np.array([0,3])
f=np.array([1.5 ,0])

In [34]:
from numpy import linalg as la 
de = la.norm(d-e)
de2= la.norm(d-f)
de3= la.norm(e-f)

print(de)
print(de2)
print(de3)

3.0
1.5
3.3541019662496847


In [8]:
arr = np.array([0, 2, 4, 5, 3, 1, 5, 6, 7, 9])

# Replace the odd numbers with their negative counterparts
arr[arr % 2 != 0] *= -1

print(arr)

[ 0  2  4 -5 -3 -1 -5  6 -7 -9]


In [15]:
np.save('aray_a',a)



In [16]:
#multiple array files 

np.savez('multi_ab', arr1=a, arr2=b)

In [17]:
# save array to txt file 

np.savetxt('array_a.txt',a)

In [ ]:
#conversion specifire is %d , it specifing that conversion should be here an INT in this example, %s tjats for string , 
# %f thats for float . 
np.savetxt('array2.txt', array=a , delimiter=',', fmt='%d')

In [18]:
#save an array in csv.file %d is integer

np.savetxt('array_a2.csv',a, delimiter=',', fmt='%d')

In [19]:
# load npy file 

anpy= np.load('aray_a.npy')

print(anpy)



[[1 2 5]
 [7 1 3]]


In [21]:
# load a file  the npz file

content= np.load('multi_ab.npz')

anpz=content['arr1']

bnpz=content['arr2']

print(anpz)

[[1 2 5]
 [7 1 3]]


In [26]:
# IMPORT TXT FILE

Attxt1= np.loadtxt('array_a.txt')

print(Attxt1)

[[1. 2. 5.]
 [7. 1. 3.]]


In [27]:
#import csv file.


ACsv=np.loadtxt('array_a2.csv', delimiter=',')

print(ACsv)

[[1. 2. 5.]
 [7. 1. 3.]]


In [ ]:
#row_header= ['row1' , 'row2']

#df= np.array([[1,2] , [4,5]])

#np.array(row_header)[:np.newaxis]
#np.hstack((row_header,df))

In [156]:
df = np.array([[1,2,3], [4,5,6], [7,8,9]])



#adding column header

header = np.array([['a'], ['b'], ['c'] , ['d']]) 

row_header = [['row1' , 'row2' , 'row3']]

#concatenate header and the row with df 


df= np.vstack((row_header, df))
df=np.hstack((header, df))



print(df)





[['a' 'row1' 'row2' 'row3']
 ['b' '1' '2' '3']
 ['c' '4' '5' '6']
 ['d' '7' '8' '9']]


In [158]:
import numpy as np

df = np.array([[1,2,3], [4,5,6] ,[7,8,9]])
header = np.array([['a'], ['b'], ['c']])
#row_header = np.array((['row1', 'row2' , 'row3']))
row_header = np.array([['row1' , 'row2' , 'row3','row4']])


df= np.hstack((header, df)) 
df= np.vstack((row_header,df))

print(df)
print(header.ndim)
print(row_header.ndim)

[['row1' 'row2' 'row3' 'row4']
 ['a' '1' '2' '3']
 ['b' '4' '5' '6']
 ['c' '7' '8' '9']]
2
2
