In [6]:
import numpy as np


In [3]:
number_row=2
number_col=3


arrays5= 5* np.ones((number_row, number_col))
arrays5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [7]:
start=10
end=25
step=3
evenly_step=np.arange(start,end,step)

evenly_step

array([10, 13, 16, 19, 22])

In [8]:
identity=np.eye(2)

identity

array([[1., 0.],
       [0., 1.]])

In [10]:
random01=np.random.random((2,3))

random01

array([[0.67086954, 0.67395886, 0.87142254],
       [0.05057194, 0.25504758, 0.87740561]])

In [14]:
randRange=np.random.randint(0,10,(2,3))
randRange

array([[3, 0, 7],
       [2, 6, 9]])

In [17]:
a=np.array([[2,3,5], [2,3,6]])

a





array([[2, 3, 5],
       [2, 3, 6]])

In [19]:
a.dtype

a.shape

(2, 3)

In [22]:
arr = [0,2,4,5,3,7,8,9,5,1]

for i in range (len(arr)):
    if arr[i]%2== 1:
        arr[i]= -arr[i]


oddnumbers= [x for x in arr if x %2==1]

print(oddnumbers)

[-5, -3, -7, -9, -5, -1]


In [14]:
a = np.array([[1 ,2 , 5] , [7,1,3]])
b = np.array([[4,7,8],     [1,5,7]])
c= np.array([[1,2,3],      [8,9,10]])
# stacking arrays together horizontal(column) or vertical(rows) 
abc=np.hstack([a,b,c])
print(abc)

cab=np.vstack([a,b,c])


[[ 1  2  5  4  7  8  1  2  3]
 [ 7  1  3  1  5  7  8  9 10]]


In [13]:
#concat when you put 1 then axis=1 that will use columns , 0 default use vertical 

ab= np.concatenate((a,b) , axis=1)
print(ab)

[[1 2 5 4 7 8]
 [7 1 3 1 5 7]]


In [ ]:
# .npy numpy binary file use to save only sinlge numpy array 
# .npz numpy compressed archive use to save numpy array inside single file 

In [24]:
add1=a+b

add1

array([[ 5,  9, 13],
       [ 8,  6, 10]])

In [5]:
#dot product

b1 = np.array([[4,6] , [2,3] , [2,3]])

dotp= a.dot(b1)

dotp

NameError: name 'np' is not defined

In [28]:
d = np.array([0,0])
e= np.array([0,3])
f=np.array([1.5 ,0])

In [34]:
from numpy import linalg as la 
de = la.norm(d-e)
de2= la.norm(d-f)
de3= la.norm(e-f)

print(de)
print(de2)
print(de3)

3.0
1.5
3.3541019662496847


In [8]:
arr = np.array([0, 2, 4, 5, 3, 1, 5, 6, 7, 9])

# Replace the odd numbers with their negative counterparts
arr[arr % 2 != 0] *= -1

print(arr)

[ 0  2  4 -5 -3 -1 -5  6 -7 -9]


In [15]:
np.save('aray_a',a)



In [16]:
#multiple array files 

np.savez('multi_ab', arr1=a, arr2=b)

In [17]:
# save array to txt file 

np.savetxt('array_a.txt',a)

In [ ]:
#conversion specifire is %d , it specifing that conversion should be here an INT in this example, %s tjats for string , 
# %f thats for float . 
np.savetxt('array2.txt', array=a , delimiter=',', fmt='%d')

In [18]:
#save an array in csv.file %d is integer

np.savetxt('array_a2.csv',a, delimiter=',', fmt='%d')

In [19]:
# load npy file 

anpy= np.load('aray_a.npy')

print(anpy)



[[1 2 5]
 [7 1 3]]


In [21]:
# load a file  the npz file

content= np.load('multi_ab.npz')

anpz=content['arr1']

bnpz=content['arr2']

print(anpz)

[[1 2 5]
 [7 1 3]]


In [26]:
# IMPORT TXT FILE

Attxt1= np.loadtxt('array_a.txt')

print(Attxt1)

[[1. 2. 5.]
 [7. 1. 3.]]


In [27]:
#import csv file.


ACsv=np.loadtxt('array_a2.csv', delimiter=',')

print(ACsv)

[[1. 2. 5.]
 [7. 1. 3.]]


In [ ]:
#row_header= ['row1' , 'row2']

#df= np.array([[1,2] , [4,5]])

#np.array(row_header)[:np.newaxis]
#np.hstack((row_header,df))

In [2]:
df = np.array([[1,2,3], [4,5,6], [7,8,9]])



#adding column header

header = np.array([['a'], ['b'], ['c'] , ['d']]) 

row_header = [['row1' , 'row2' , 'row3']]

#concatenate header and the row with df 


df= np.vstack((row_header, df))
df=np.hstack((header, df))



print(df)





[['a' 'row1' 'row2' 'row3']
 ['b' '1' '2' '3']
 ['c' '4' '5' '6']
 ['d' '7' '8' '9']]


In [1]:
import numpy as np

df = np.array([[1,2,3], [4,5,6] ,[7,8,9]])
header = np.array([['a'], ['b'], ['c']])
#row_header = np.array((['row1', 'row2' , 'row3']))
row_header = np.array([['row1' , 'row2' , 'row3','row4']])


df= np.hstack((header, df)) 
df= np.vstack((row_header,df))

print(df)
print(header.ndim)
print(row_header.ndim)

[['row1' 'row2' 'row3' 'row4']
 ['a' '1' '2' '3']
 ['b' '4' '5' '6']
 ['c' '7' '8' '9']]
2
2


In [1]:
import numpy as np 

In [9]:
df = np.array([[1,2,3], [4,5,6], [7,8,9]])

# round the array 1 decimal place 

df= np.around(df, decimals=1)

#add column headers 

column_headers= ['col1', 'col2', 'col3']
#add row headers 
row_headers=[['---'] , ['row1'] , ['row2'] ,['row3']]

#combine column and row header

df_with_headers=np.vstack([column_headers,df])

df_with_row=np.hstack([row_headers,df_with_headers])

#save file txt 

np.savetxt('df.csv', df_with_row, delimiter=',',fmt='%s')


print(df_with_row)

[['---' 'col1' 'col2' 'col3']
 ['row1' '1' '2' '3']
 ['row2' '4' '5' '6']
 ['row3' '7' '8' '9']]


In [16]:
a= np.array([10,19,26,78,87,99])

print(a)


b=[1,3,5]

print(a[b]) # using b as an index to array a 


even=np.argwhere(a%2==0).flatten() #  flatten array to 1D and look for only even numbers 

print(a[even]) # checking whole a array thru using even variable, where was method to check if numbers are odd/even




[10 19 26 78 87 99]
[19 78 99]
[10 26 78]


In [20]:
a= np.arange(1,7) # printing array with range from 1 number included but end number excluded

print(a) # 1 to 6 array

print(a.shape) # shape showing you what array you got this is 1 D array with 6 column

b=a.reshape((2,3)) # you use the 1 to 6 array and RESHAPE it by going form 1D to 2D with 2 rows and 3 columns
print(b) 

#c=a.reshape((2,4))  you CANNOT do that because  there's 'not enough  numbers  you can do 3,2 means 3 rows to columns



[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]


In [27]:
a = np.arange(1,7)
print(a)

b= a[np.newaxis, :] # you getting 2D array  which is 1 row 6 columns colon is saying I want all columns add me new row/ make it 2d
print(b)
print(b.shape)

b= a[:, np.newaxis] # you getting  2D array which is  6 rows and 1 column  it take all rows and create 2d array which is 1 col , 6 rows
print(b)
print(b.shape)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [42]:

a=np.array([[1,2], [3,4]])


b=np.array([[5,6]])

c=np.concatenate((a,b.T), axis=1) # axis=None will just add them at the end and make it 1D flatten array,  axis=0 will keep 2 columns and 3 rows
# if axis 1 will give an error because they are NOT EQUAL !! to avoid it you can do a,b.T transpose (turn around ) array
print(c)



[[1 2 5]
 [3 4 6]]


In [53]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

#hstack horizontal
c= np.hstack((a, b))

print(c)

#vstack vertical

d=np.vstack((a,b))
print(d)

x=np.array([[1,2,3,4] , [5,6,7,8] , [1,2,3,4] , [5,6,7,8]])
y=np.array([5,6,7,8]) 
z= x+y # whats happening here is BROADCASTING it  added our y array to x array like you can see at z , it is (4,4) like the
# x was at start but it ADDED value from y to x arrays !
print(z)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[ 6  8 10 12]
 [10 12 14 16]
 [ 6  8 10 12]
 [10 12 14 16]]


In [64]:
a=np.array([[8,7,9,10,11,12,13] , [22,23,24,25,26,27,28]])
print(a)
print(a.sum()) # it added all together but you can adde via AXIS !!
print(a.sum(axis=0))# addin by column means 8 +22 =30 , 7 +23 =30 , 9+24 =33 and going further
print(a.sum(axis=1))#adding by rows  [8+7+9+10+11+12+13]=70  other one is 175

print(a.mean(axis=0)) #mean: Compute the arithmetic mean (average) of the given data (array elements) along the specified axis

[[ 8  7  9 10 11 12 13]
 [22 23 24 25 26 27 28]]
245
[30 30 33 35 37 39 41]
[ 70 175]
[15.  15.  16.5 17.5 18.5 19.5 20.5]


In [75]:
c=np.array([[8,7,9,10,11,12,13] , [22,23,24,25,26,27,28]])

print(c.std(axis=0))
print(np.std(a,axis=0))  #same result it does return the standard deviation, a measure of the spread of a distribution, of the array elements

print(c.var(axis=0)) #We get the Variance by calculating the sum of all values in a Numpy array divided by the total number of values.

print(c.dtype)
# we can force to change the datatype by using dtype=  and then just change it ! 

x=np.array([8,7,9,10,11,12,13] , dtype=np.float32)

print(x.dtype) #from 32 to 64 bits changed with dtype=np.int64

print(x)# here showing as float I did put dtype=np.float32 on x array



[7.  8.  7.5 7.5 7.5 7.5 7.5]
[7.  8.  7.5 7.5 7.5 7.5 7.5]
[49.   64.   56.25 56.25 56.25 56.25 56.25]
int32
float32
[ 8.  7.  9. 10. 11. 12. 13.]


In [89]:
e=np.zeros([2,3]) #building an array filled with zeros 2 rows 3 columns
print(e)

f=np.ones([2,3])#building an arry filled with ones 
print(f)

g=np.full((2,3),8) #what this does is creating array 2 rows 3 columns with any number you want and fill it up !
print(g)

h=np.eye(3,k=1)#create  2D 3x3 array  which put ones diagonally but you can change it  with key value you want default remove key value!
print(h)

h=np.eye(3)#you cans see ones going from left corner to bottom right corner
print(h)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8]
 [8 8 8]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [103]:
a=np.linspace(0,10,5) #first number start , second the end , third number is how many steps will take from start to end.

print(a)


b=np.random.random((3,2))#you will get 3 rows , 2 columns of random numbers from 0 to 1 
print(b)
c=np.random.randint(5,10, size=(3,2))#first number is start , second is end which is NOT included. size is size of our array
#example c you can put just one number at the beggining  this will give 0 as default START VALUE .
print(c)
d=np.random.choice(5, size=10)#taking  ten random numbers from 0 set as default beggining upto max 5 

print(d)

e=np.random.choice([-8,-7,-6],size=5)

print(e)

[ 0.   2.5  5.   7.5 10. ]
[[0.77174313 0.1307158 ]
 [0.91411003 0.75943553]
 [0.18969977 0.50655992]]
[[7 6]
 [9 6]
 [7 6]]
[0 4 3 3 1 1 4 1 2 0]
[-7 -7 -6 -8 -7]


In [ ]:
a=np.array([[1,2], [3,4]])

In [113]:
# how to load txtfile  np.genfromtxt

data = np.genfromtxt('df.csv', delimiter=',', skip_header=1, dtype=[('col1', 'i4'), ('col2', 'i4'), ('col3', 'i4'), ('col4','i4')])
# what it's happening we opening df.csv file , with delimiter , like in SQL , skip_header just removing name of column that I can open file
# after that I set dtype for columns which is i4 INTEGER 4 bytes or 32 bit integer  same thing 
print(data.shape)#the -1 in each paretheses are replacement for row1 row 2 row 3

(3,)
